- name: data types
  hosts:  frontend
  vars:
    Course: Devops
    Duration: 120
    is_live:  true
    tools:
    - "linux"
    - "AIX"
    - Ansible
    concepts:
      cloud:  aws
      am: ansible

  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg:  "Course name: {{ Course}}, Duration is: {{ Duration }}, toos are: {{ tools }}, concepts is: {{ concepts }}"