- name: condition checking
  hosts:  frontend
  vars:
    number: 5
  tasks:
  - name: checking number is less than 10 or not
  ansible.builtin.debug:
    msg:  "Given Number {{ number }} is less than 10"
  when: number < 10