- name: Condition checking
  hosts:  frontend
  vars:
    number: 2
  tasks:
  - name: checking number is less than 10 or not
    ansible.builtin.debug:
      msg:  "Given number {{ number }} is less than 5"
    when: number  < 10

