- name: loop the names
  hosts:  frontend
  tasks:
  - name: print the names
    ansible.builtin.debug:
      msg:  " Hello {{ item }}"
    loop:
      - Reddiah
      - Likith
      - Sunitha
      - Geethika
