- name: install packages
  hosts:  frontend
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state:  installed
    loop:
    - git  
    - wget
    - nginx
    - mysql
