- name: function
  hosts:  frontend
  vars:
    technologies: Devops, Linux, Shell, Ansible
    name: Reddiah
    gmail:  reddeiah18g@gmail.com
    ipaddress:  "50.19.36.168"
    tags:
      Application:  payment
      environment:  Dev
    listTags:
    - key:  Application
      value:  payment
    - key:  environment
      value:  Dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg:  " Hello, {{ name | default('Reddiah') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg:  "Technologies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg:  "Tags are: {{ tags | dict2items }}"

  - name: ipaddress checking
    ansible.builtin.debug:
      msg:  "{{ ipaddress | ansible.utils.ipv4 }}"
    ignore_errors:  true

  - name: grep for root
    ansible.builtin.shell:  cat /etc/passwd | grep root
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg:  "{{ command_output }}"

  - name: redirect the output
    ansible.builtin.command:  ls -ltr > /tmp/output.txt